name: Upload iOS SFA Quick Start build on appeitize

on:
  push:
    branches:
      - main
    paths:
      - "single-factor-auth-ios/sfa-ios-quick-start/**"

defaults:
  run:
    working-directory: ./single-factor-auth-ios/sfa-ios-quick-start/

jobs:
  build-and-upload:
    runs-on: macos-latest
    steps:
      - name: Build iOS simulator build
        run: |
          xcodebuild -scheme ios-firebase-example -sdk iphonesimulator -derivedDataPath build

      - name: Compress iOS build
        run: |
          tar -czf ios_build.tar.gz build/Build/Products/Debug-iphonesimulator

      - name: Upload iOS build to Appeitize
        uses: appetizeio/github-action-appetize@v1.0.1
        with:
          apiToken: ${{ secrets.APPETIZE_SECRET_KEY }}
          publicKey: ${{ secrets.IOS_SFA_QUICK_START_PUBLIC_KEY }}
          appFile: ./single-factor-auth-ios/sfa-ios-quick-start/ios_build.tar.gz
          platform: "ios"
